### ISSUE TITLE
Idea: add eslint-plugin-react-refresh

### ISSUE THREAD

**Issue by lew** [Austrian-Web-Services/config#5]
As per https://github.com/vitejs/vite-plugin-react-swc:

For React refresh to work correctly, your file should only export React components. The best explanation I've read is the one from the [Gatsby docs](https://www.gatsbyjs.com/docs/reference/local-development/fast-refresh/#how-it-works).

If an incompatible change in exports is found, the module will be invalidated and HMR will propagate. To make it easier to export simple constants alongside your component, the module is only invalidated when their value changes.

**You can catch mistakes and get more detailed warning with this [eslint rule](https://github.com/ArnaudBarre/eslint-plugin-react-refresh).**

**Comment by NimmLor** [comment]
added in v3
